# application.properties

# Application settings
quarkus.application.name=validation-as-a-service

# Logging (RNF-04)
quarkus.log.console.level=INFO
quarkus.log.category."br.gov.serpro".level=DEBUG
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n

# Open API Config
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# %dev Profile (HSQLDB)
%dev.quarkus.datasource.db-kind=other
%dev.quarkus.datasource.jdbc.driver=org.hsqldb.jdbc.JDBCDriver
%dev.quarkus.datasource.jdbc.url=jdbc:hsqldb:mem:vaas;DB_CLOSE_DELAY=-1
%dev.quarkus.datasource.username=sa
%dev.quarkus.datasource.password=
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.hibernate-orm.dialect=org.hibernate.dialect.HSQLDialect

# %prod Profile (PostgreSQL)
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/vaas}
%prod.quarkus.datasource.username=${DB_USER:postgres}
%prod.quarkus.datasource.password=${DB_PASSWORD:postgres}
%prod.quarkus.hibernate-orm.database.generation=validate
%prod.quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect

# Default dialect mapping correctly
quarkus.hibernate-orm.dialect=org.hibernate.dialect.HSQLDialect
